In [5]:
#import numpy library or module 
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [9]:
#create 1-D numpy array
import numpy as np
a1=np.array([1,2,3,4])
print(a1)
print(type(a1))
print(a1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [11]:
import numpy as np
a1=np.array(["A",2,3,4])
print(a1)
print(type(a1))
print(a1.shape)

['A' '2' '3' '4']
<class 'numpy.ndarray'>
(4,)


In [39]:
#create 2-D array in numpy
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [15]:
#2-D array with our data
a3=np.array([[1,"JITESH",9.8],
       [2,"SIDDHARTHA",9.5]])
print(a3)
print(type(a3))
print(a3.shape)

[['1' 'JITESH' '9.8']
 ['2' 'SIDDHARTHA' '9.5']]
<class 'numpy.ndarray'>
(2, 3)


In [31]:
#Reshape
a=np.array([1,2,3,4])
b=a.reshape([2,2])
print(b)
print(b.shape)


[[1 2]
 [3 4]]
(2, 2)


In [49]:
#create an array with arange()
c=np.arange(3,5)
print(c)
type(c)

[3 4]


numpy.ndarray

In [70]:
#use of around()
d=np.array([1.234,3.415,5.565])
print(d)
np.around(d,1)

[1.234 3.415 5.565]


array([1.2, 3.4, 5.6])

In [72]:
#use of sqrt()
d=np.array([1.234,2.345,3.456])
print(d)
print(np.around(np.sqrt(d),2))

[1.234 2.345 3.456]
[1.11 1.53 1.86]


In [101]:
import numpy as np
a6=np.array([[1,2,3,4],[5,6,7,8,np.NaN]])
print(a6)
print(a6.shape)
print(a6.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [113]:
#print matrix array
a2=np.array([[1,2,3],[4,5,6],[1,6,12]])
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 1  6 12]]


In [115]:
#sum of matrix of array
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[ 6 15 19]
[ 6 13 21]


In [122]:
print(a2)
print(a2.mean(axis = 0))
print(a2.mean(axis = 1))

[[ 1  2  3]
 [ 4  5  6]
 [ 1  6 12]]
[2.         4.33333333 7.        ]
[2.         5.         6.33333333]


In [126]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [136]:
import numpy as mp
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
#perform matrix multiplication
C=np.matmul(A,B)
print(C)
print(A.T)
print(B.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [138]:
a4 = np.array([[1,2,3],[4,5,6],[3,2,1],[6,5,4]])
print(a4)

[[1 2 3]
 [4 5 6]
 [3 2 1]
 [6 5 4]]


In [150]:
print(a4[1][1])

SyntaxError: invalid syntax (3730989072.py, line 2)